name: CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    strategy:
      matrix:
        python-version: [ 3.10.0 ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: PYTHONPATH=. pytest tests

      - name: Run code quality tests
        continue-on-error: true
        run: flake8 --ignore=E501

      - name: Run security tests
        continue-on-error: true
        run: |
          safety check --full-report
          bandit day*.py
